language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - printf "DB_DRIVER=mysql\nDB_HOST=localhost\nDB_NAME=wordpress\nDB_USER=root\nDB_PASSWORD=" > .env
  - mysql -e 'create database wordpress;'
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
